### ISSUE TITLE
Explaination

### ISSUE THREAD

**Issue by manan904** [rupav/Sentiment-Analysis#5]
Hi @rupav ... I'd like to know the working of the project and what is the main aim of this project. Could'nt understand by the readme file.

Thanks a lot!

Manan Manwani

**Comment by rupav** [comment]
Hi @manan904, this repository is basically for a project on 'twitter sentiment analysis on a given trend ,location wise' (based on learning from Coding Ninjas) . Readme file is not well maintained yet, because its not open sourced yet :).

**Comment by manan904** [comment]
If it is not "open-sourced" then why is it available on github ?

**Comment by rupav** [comment]
@manan904 
As written in Readme, its just for tracking the work of collaborators. That's why we used Github :) .

**Comment by manan904** [comment]
Okay!....
Really liked the project idea!!!..Found it quite interesting!

Good Luck!
